### PR TITLE
Move broken Parallel.gdistances function to Experimental submodule

### PR DESCRIPTION
**Pull request by simonschoelly**
The `Parallel.gdistances`  functions seems to have some incorrect assumptions about threaded memory. This leads to tests failing from time to time. In order to not completely throw away the code, this PR moves it to the `Experimental.Parallel` submodule and deactivates the tests for this function.

See #10

### CODE REVIEW

**Review by etiennedeg — CHANGES_REQUESTED** [review]
There is also `gdistances` tests in 
Graphs.jl/test/traversals/bfs.jl (lines 29-35)

`gdistances` should not be globally exported, but only exported in Experimental module.

We should also reflect this change in the documentation (`gdistances` appears in 
Graphs.jl/docs/src/pathing.md for example)

`period` is calling `gdistances`, what should we do about it ?

@ViralBShah  mentionned that he also saw `bfs` failing, but I couldn't find such failing test.

**Comment by ViralBShah** [comment]
The `bfs` failures only happen sporadically in CI for me. I could not reproduce on my own machine.

**Comment by simonschoelly** [comment]
The tests in `Graphs.jl/test/traversals/bfs.jl` are for the non-parallel version of `gdistances`  which is is not broken, so it still should be exported:
https://github.com/JuliaGraphs/Graphs.jl/blob/abdfceb0ec54990e7ce30040e1902aa3e1a1e2f3/src/traversals/bfs.jl#L126-L141

**Comment by ViralBShah** [comment]
IIRC, it was parallel bfs that was broken - not the sequential one.

**Comment by simonschoelly** [comment]
The testset in which the failing `gdistances` test where defined, is called
https://github.com/JuliaGraphs/Graphs.jl/blob/abdfceb0ec54990e7ce30040e1902aa3e1a1e2f3/test/parallel/traversals/gdistances.jl#L1
Is it possible, that this is the reason why you think that `bfs` fails from time to time?

**Comment by ViralBShah** [comment]
Yes that would explain it. I was just going by what I was seeing in the logs.

**Comment by etiennedeg** [comment]
Ok, my bad, all my remarks were on sequential `gdistances`, so I think its ok for me. (gdistances was not even mentionned in the documentation of parallel algorithms)

**Comment by simonschoelly** [comment]
Thanks for reviewing :) Will merge this now, so hopefully we won't see that many failing tests anymore.

**Pull request merged**
