### PR TITLE
Change test outputs 

### PR DESCRIPTION
**Pull request by aurorarossi**
As I wrote in issue #181, the test outputs were hiding the summary table. 
With this pull request I hid the long outputs and I set `verbose = true` to have more readable information in the summary table.

### CODE REVIEW

**Comment by aurorarossi** [comment]
With this PR the output is the following:
image
I attach two screenshot of the current output:

image

image

**Comment by aurorarossi** [comment]
Another option  removing `verbose = true`  would be:
image

**Review by gdalle — APPROVED** [review]

**Comment by simonschoelly** [comment]
@gdalle I would have appreciated if that would have still been left open for discussion.

**Comment by simonschoelly** [comment]
Ah, I realized that I only communicated on slack, so there was no trace of me reviewing

**Comment by gdalle** [comment]
> @gdalle I would have appreciated if that would have still been left open for discussion.

My bad @simonschoelly, I thought it was sufficiently minor to approve directly and I didn't think of any downsides to having more detailed test outputs. I didn't see the discussion on Slack though, I'll go there to check it out. Mea culpa!

**Comment by simonschoelly** [comment]
@gdalle No sorry, this is totally my fault. I had completely forgotten that I never started doing the code review here on github and was still in the progress of trying to figure out in what way the test outputs were changing. Of course it should not be necessary to double check on slack.

**Comment by gdalle** [comment]
Alright then! I haven't been very Slacking recently but it should get better soon :)

**Pull request merged**
