### PR TITLE
Graphs.jl 2.0

### PR DESCRIPTION
**Pull request by etiennedeg**
Here is a first draft for the Graphs 2.0, in order to get something actionable. 

For the moment, there is not much in it: the implementation of major parts of the new interface, new interface applied to SimpleGraphs, and a rewriting of `a_star` following the new interface to test it a little bit. I haven't tested anything for the moment.

In order to keep the discussion on the new API focused in one place, I will detail my thoughts and observations about the new interface and its practicalities in the [API 2.0 discussion ](https://github.com/JuliaGraphs/Graphs.jl/issues/146), see [this comment](https://github.com/JuliaGraphs/Graphs.jl/issues/146#issuecomment-1597332129) for some details on this draft.

### CODE REVIEW

**Comment by gdalle** [comment]
Todo: migrate this to GraphsBase.jl

**Comment by gdalle** [comment]
@etiennedeg do you need help for the transfer to GraphsBase? happy to lend a hand

**Comment by etiennedeg** [comment]
Sorry, I should have done it earlier, I will try to do it quickly (probably not today, but I should find some time tomorrow)

**Comment by gdalle** [comment]
No rush, I was just checking in! Got a CS sudent intern starting on September 19th who will give us a hand on this behemoth of a project ;)

**Comment by gdalle** [comment]
Closing in favor of https://github.com/JuliaGraphs/GraphsBase.jl/pull/9

**Pull request closed without merging**
