### PR TITLE
Algorithm for finding the longest path of a DAG

### PR DESCRIPTION
**Pull request by matheusdiogenesandrade**
DAG longest path algorithm.

### CODE REVIEW

**Comment by matheusdiogenesandrade** [comment]
Could someone help me with this test case?
```
Code formatting (JuliaFormatter.jl): Test Failed at /home/runner/work/Graphs.jl/Graphs.jl/test/runtests.jl:24
  Expression: format(Graphs; verbose = false, overwrite = false, ignore = ["vf2.jl"])
```
Even locally I am not able to pass it.

**Comment by aurorarossi** [comment]
I had the same problem (I solved it in a PR that is still in progress).
It should work by removing the parentheses in the runtest.jl file here: `ignore = ["vf2.jl"]` --> `ignore = "vf2.jl"`.

**Comment by simonschoelly** [comment]
> I had the same problem (I solved it in a PR that is still in progress). It should work by removing the parentheses in the runtest.jl file here: `ignore = ["vf2.jl"]` --> `ignore = "vf2.jl"`.

If you have time, maybe you can create a separate PR just for that change, so that we could merge it quickly?

**Comment by matheusdiogenesandrade** [comment]
@aurorarossi Thanks, just made this, let's see now. @simonschoelly, I pushed the changes, what do you mean by making another PR? I am sorry, but this is my first open-source contribution, thus I am not used to some usual tasks.

**Comment by aurorarossi** [comment]
> @aurorarossi Thanks, just made this, let's see now. @simonschoelly, I pushed the changes, what do you mean by making another PR? I am sorry, but this is my first open-source contribution, thus I am not used to some usual tasks.

I think that @simonschoelly was referring to me. I will take care of it.

**Comment by matheusdiogenesandrade** [comment]
@aurorarossi thanks. Folks, concerning this last checking (https://github.com/JuliaGraphs/Graphs.jl/pull/209/checks?check_run_id=10444689306), can someone help me to understand why it is failing?

Thanks.

**Comment by aurorarossi** [comment]
It means that some lines are not covered by a test.

**Comment by matheusdiogenesandrade** [comment]
@aurorarossi Thank you! So I think that providing unitary tests (as I did https://github.com/JuliaGraphs/Graphs.jl/pull/209/files#diff-9c1223f541fc1697a6f988c8c086087d93a6467d5f7da2a2d9b2cd612c92184f) is not enough. What sort of additional tests should I provide?

Regards.

**Comment by matheusdiogenesandrade** [comment]
@aurorarossi never mind, I forgot to insert my test file in the `runtest.jl`.

**Comment by matheusdiogenesandrade** [comment]
Sorry, I am quite lost on how to solve these conflicts. Does anyone have any suggestion? 

Thnx, and regards.

**Comment by gdalle** [comment]
@matheusdiogenesandrade thank you for the contribution!

I brought it up to speed with the latest changes and I simplified the syntax a bit. The doctest is still failing, but it would be interesting for you to try and figure out why :)

As a side note, you don't need to declare the type of every object you create, in most cases Julia will infer it for you :)

**Comment by matheusdiogenesandrade** [comment]
> @matheusdiogenesandrade thank you for the contribution!
> 
> I brought it up to speed with the latest changes and I simplified the syntax a bit. The doctest is still unreliable (it might fail or succeed), but it would be interesting for you to try and figure out why on your own :) If you don't find the reason, I can help.
> 
> As a side note, you don't need to declare the type of every object you create, in most cases Julia will infer it for you!

Thanks. I think I solved the issue.

**Comment by gdalle** [comment]
You did but you overwrote my previous changes to the longest paths source file in the process. Can you revert your latest commit and just change the necessary seed?

More tests would also be welcome with a different topological order

**Comment by matheusdiogenesandrade** [comment]
> You did but you overwrote my previous changes to the longest paths source file in the process. Can you revert your latest commit and just change the necessary seed?
> 
> More tests would also be welcome with a different topological order


Sorry, it was an accident, but now I think it is ok. Are the erros with the nightly julia version normal?

Regards.

**Review by gdalle — APPROVED** [review]

**Comment by matheusdiogenesandrade** [comment]
Thank very much everyone!

**Comment by rjdverbeek** [comment]
Having the longest path algorithm for directed acyclic graphs means that we also have the shortest path algorithm for DAG.

`
function dag_shortest_path(
    g::::IsDirected,
    distmx::AbstractMatrix=weights(g);
    topological_order=topological_sort_by_dfs(g),
) =
dag_longest_path(
        g,
        -distmx;
        topological_order
    )
`

**Pull request merged**
