### PR TITLE
fix erdos renyi generator

### LINKED ISSUE #173: error in erdos_renyi generator
Some branches of the `erdos_renyi` function produce an error:
```julia
julia> erdos_renyi(4, 6, seed=1)
ERROR: ArgumentError: Cannot specify both, seed and rng
Stacktrace:
 [1] rng_from_rng_or_seed(rng::Random.MersenneTwister, seed::Int64)
   @ Graphs ~/.julia/packages/Graphs/2JiDT/src/utils.jl:68
 [2] SimpleGraph{Int64}(nv::Int64, ne::Int64; rng::Random.MersenneTwister, seed::Int64)
   @ Graphs.SimpleGraphs ~/.julia/packages/Graphs/2JiDT/src/SimpleGraphs/generators/randgraphs.jl:29
 [3] SimpleGraph(nv::Int64, ne::Int64; rng::Random.MersenneTwister, seed::Int64)
   @ Graphs.SimpleGraphs ~/.julia/packages/Graphs/2JiDT/src/SimpleGraphs/generators/randgraphs.jl:45
 [4] SimpleGraph{Int64}(nv::Int64, ne::Int64; rng::Nothing, seed::Int64)
   @ Graphs.SimpleGraphs ~/.julia/packages/Graphs/2JiDT/src/SimpleGraphs/generators/randgraphs.jl:30
 [5] #SimpleGraph#21
   @ ~/.julia/packages/Graphs/2JiDT/src/SimpleGraphs/generators/randgraphs.jl:45 [inlined]
 [6] #erdos_renyi#26
   @ ~/.julia/packages/Graphs/2JiDT/src/SimpleGraphs/generators/randgraphs.jl:166 [inlined]
 [7] top-level scope
   @ REPL[18]:1
 [8] top-level scope
   @ ~/.julia/packages/CUDA/DfvRa/src/initialization.jl:52

julia> erdos_renyi(10, 6, seed=1) # no error with more nodes
{10, 6} undirected simple Int64 graph
```
This is on julia v1.8.1, Graphs v1.7.3

### PR DESCRIPTION
**Pull request by CarloLucibello**
fix #173

### CODE REVIEW

**Comment by simonschoelly** [comment]
Ups, should have caught that when reviewing #170.

**Review by simonschoelly — APPROVED** [review]

**Comment by simonschoelly** [comment]
Thanks

**Comment by CarloLucibello** [comment]
thanks for the quick review! Can you tag a patch release?

**Comment by simonschoelly** [comment]
Sure: https://github.com/JuliaRegistries/General/pull/68944

**Pull request merged**
