### PR TITLE
Migrate flow algorithms from GraphsFlows

### PR DESCRIPTION
**Pull request by gdalle**
Take everything in [GraphsFlows.jl](https://github.com/JuliaGraphs/GraphsFlows.jl) and put it in Graphs.jl.

This is half of the solution to https://github.com/JuliaGraphs/Graphs.jl/issues/108

- [x] remove the min cost flow part, which relies on JuMP.jl (see GraphsOptim.jl)
- [x] copy-paste the code to `src/flows`
- [x] copy-paste the tests to `test/flows`
- [x] copy-paste the docs and put it in `docs/src/flows.md`
- [x] modify `src/Graphs.jl` and `test/runtests.jl` and `docs/make.jl` to include necessary files
- [x] format everything
- [x] modify docs to include private names in a separate section
- [x] modify nearly all tests to use generic graphs

@matbesancon since it's your code do you have anything to say about this?

### CODE REVIEW

**Comment by gdalle** [comment]
Tests are failing because type inference in 1.6 is less good

**Comment by matbesancon** [comment]
I'm good with it yup thanks!

**Comment by gdalle** [comment]
This is the part that is not well inferred:

```julia
@traitfn residual(flow_graph::::IsDirected) = Graphs.DiGraph(Graphs.Graph(flow_graph))
```

**Comment by simonschoelly** [comment]
Can I suggest that we move everything initially to the `Experimental` submodule. This way
* We won't have any name clashes as long as we don't export anything.
* We don't initially guarantee that the API for flows is stable so we still can't change things
* It is easier to track what we change from `GraphFlows.jl` when we do this in a separate PR instead of doing it in this one, where we don't have a history.

**Comment by gdalle** [comment]
That's a good idea but as for tracking changes, beyond renaming I only did the bare minimum so that the code could run. A lot of initial changes are gonna be necessary even in the `Experimental` submodule

**Comment by gdalle** [comment]
Also I'm a bit lazy at the prospect of redoing all of these necessary changes from scratch just so we can track the renaming, but I understand your point

**Comment by gdalle** [comment]
Closing this to reopen a cleaner PR with visible changes

**Pull request closed without merging**
