### PR TITLE
[Port] fix possible NaN in closeness centrality. Closes #1555

### PR DESCRIPTION
**Pull request by etienneINSA**
This is a port of [#1568](https://github.com/sbromberger/LightGraphs.jl/pull/1568/commits)

### CODE REVIEW

**Comment by ViralBShah** [comment]
Seems like tests that otherwise don't fail have failed on windows (but no elsewhere). Can you review the Windows failure and see if this is ok?

**Comment by ViralBShah** [comment]
@etienneINSA I have invited you to the JuliaGraphs org, and to have write access to this repo. Since you have a number of open PRs, I think the project could benefit from your contributions - and hopefully write access helps.

**Comment by etienneINSA** [comment]
Thanks @ViralBShah for the invitation, I hope I can bring a modest help to this project.

@jpfairbanks This PR makes some tests fail on windows-latest. Why was it  merged ? Is it confirmed that the failed tests are not caused by this PR ?

**Comment by ViralBShah** [comment]
That issue is #10 and #50.

**Pull request merged**
